### ISSUE TITLE
Another crash on compress file.

### ISSUE THREAD

**Issue by reduz** [BinomialLLC/basis_universal#74] opened 2019-09-27 01:37 UTC
Using the standalone does not crash, but running from API again seems to do it, on this file:

[crash_stone.zip](https://github.com/BinomialLLC/basis_universal/files/3660501/crash_stone.zip)

Crash log is different than the previous one:

```
basis_compressor::basis_compressor
basis_compressor::init
basis_compressor::process
basis_compressor::read_source_images
Source image index 0 filename  1024x1024 has alpha: 0
Any source image has alpha: 0
****** Slice 0: mip 0, alpha_slice: 0, filename: "", original: 1024x1024 actual: 1024x1024
Total blocks: 65536, Total macroblocks: 16384
Total basis file slices: 1
Slice: 0, alpha: 0, orig width/height: 1024x1024, width/height: 1024x1024, first_block: 0, image_index: 0, mip_level: 0, iframe: 0
basis_compressor::validate_texture_type_constraints
basis_compressor::process_frontend
selector_codebook_bpp_est: 0.015137
basisu_frontend::init: Multithreaded: 1, NumEndpointClusters: 512, NumSelectorClusters: 512, Perceptual: 1, CompressionLevel: 1
Global sel codebook pal bits: 0, Global sel codebook mod bits: 0, Use hybrid selector codebook: 0, Hybrid codebook quality thresh: 0.000000
Endpoint refinement: 1, Hierarchical endpoint codebooks: 1, Hierarchical selector codebooks: 1, Endpoint codebook iters: 1, Selector codebook iters: 1
basisu_frontend::compress
basisu_frontend::init_etc1_images
init_endpoint_training_vectors
Begin endpoint quantization
Using 8 threads to create codebook
generate_hierarchical_codebook_threaded: 131072 training vectors, 167 unique training vectors
Limit clusterizers: 0
: thirdparty/basis_universal/basisu_enc.h:1069: bool basisu::tree_vector_quant<TrainingVectorType>::generate(uint32_t) [with TrainingVectorType = basisu::vec<6, float>; uint32_t = unsigned int]: Assertion `node.m_var == var_heap.get_top_priority()' failed.
Aborted (core dumped)
```

**Comment by richgel999** [comment] 2019-09-27 01:46
Hmm - I can't see how you're initializing the basis_compressor_params struct. I'll try your file and see what happens in a few minutes. Line 1069 is:

assert(node.m_var == var_heap.get_top_priority());

If this assert() is the problem you're seeing, I think it's a duplicate of another rare issue filed here which I'll be looking at after the next release. This issue doesn't impact the correctness of the output (but it shouldn't happen anyway).

**Comment by reduz** [comment] 2019-09-27 01:53
This is the initialization code, it runs every time an image is compressed. 
Should I just leave a singleton initialized for all images that are going to be compressed instead?

```
		basisu::basis_compressor_params params;
		params.m_multithreading = true;
		params.m_no_hybrid_sel_cb = true; //fixme, default on this causes crashes
		//params.m_disable_hierarchical_endpoint_codebooks = true;
		//params.m_no_selector_rdo = true;

		basisu::job_pool jpool(OS::get_singleton()->get_processor_count());
		params.m_pJob_pool = &jpool;

		params.m_mip_gen = false; //compressing them separately
		params.m_source_images.push_back(buimg);

		basisu::basis_compressor c;
		c.init(params);

		int buerr = c.process();
```

**Comment by richgel999** [comment] 2019-09-27 01:56
You could, but I haven't tested that. I would initialize a new instance of "basisu::basis_compressor" (and a new job pool) for each run of the compressor. As the compressor will take many hundreds of ms (or seconds) it shouldn't be a big deal.

BTW - very few folks are calling the encoder directly yet. Just you and the KTX2 devs, to my knowledge. The road is a little rougher calling the encoder directly, but any bugs you find we will fix ASAP. We've been focusing a lot on the transcoders recently.

**Comment by richgel999** [comment] 2019-09-27 01:59
Looking at your code, you need to create one instance of the "basist::etc1_global_selector_codebook" class:

basist::etc1_global_selector_codebook sel_codebook(basist::g_global_selector_cb_size, 
basist::g_global_selector_cb);

Then pass a pointer to this in the params struct:
params.m_pSel_codebook = &sel_codebook;

This always should be done.

**Comment by reduz** [comment] 2019-09-27 02:16
Thanks! it seems to be working better now (a lot more output per file) it also runs a few orders of magnitude  slower, though, so I will leave the project re-importing and will check tomorrow.

**Comment by richgel999** [comment] 2019-09-27 04:47
I've reproduced this - it's an known assert. Should be harmless and the encoder's output will be correct. I'm debugging it.

**Comment by richgel999** [comment] 2019-09-27 05:04
I've checked in the fix to the assert.

**Closed by richgel999** 2019-09-27 05:04 UTC
