### ISSUE TITLE
In concurrent transcoder, the longer the blocking time when have more mipmap levels.

### ISSUE THREAD

**Issue by PolanZ** [BinomialLLC/basis_universal#203] opened 2021-03-12 02:40 UTC
demo:
```js
// scheduler web worker
// loaded basis_transcoder.js and basis_transcoder.wasm
// create webwoker,
const worker = ...

// scheduler
// concurrent 100 times
for (let i = 100; i >=0; i--) {
  const time = performance.now();
  worker.onmessage = function () {
     console.log('trancode time: ', performance.now() - time)
  }
  worker.postMessage(somedata)
}

// basis_loader.js transcode
function transcode(id, arrayBuffer, supportedFormats, allowSeparateAlpha) {
  let basisData = new Uint8Array(arrayBuffer);

  let basisFile = new BasisFile(basisData);
  let images = basisFile.getNumImages();
  let levels = basisFile.getNumLevels(IMAGE_INDEX);
  let hasAlpha = basisFile.getHasAlpha();
  
  // ....

  // mipmap ...
  for (let mipLevel = 0; mipLevel < levels; ++mipLevel) {
    let transcodeSize = basisFile.getImageTranscodedSizeInBytes(IMAGE_INDEX, mipLevel, basisFormat);
    mipLevels.push({
      level: mipLevel,
      offset: totalTranscodeSize,
      size: transcodeSize,
      width: basisFile.getImageWidth(IMAGE_INDEX, mipLevel),
      height: basisFile.getImageHeight(IMAGE_INDEX, mipLevel),
    });
    totalTranscodeSize += transcodeSize;
  }

  postMessage({
    id: id,
    buffer: transcodeData.buffer,
    alphaBuffer: needsSecondaryAlpha ? alphaTranscodeData.buffer : null,
    webglFormat: webglFormat,
    mipLevels: mipLevels,
    hasAlpha: hasAlpha,
  }, transferList);
}
```

out console:
```
// ...
loadBasis.js:50 transcoder time 80.79999999608845
loadBasis.js:50 transcoder time 83.08999997097999
loadBasis.js:50 transcoder time 83.37499992921948
loadBasis.js:50 transcoder time 84.47499992325902
loadBasis.js:50 transcoder time 88.164999964647
loadBasis.js:50 transcoder time 90.26999992784113
loadBasis.js:50 transcoder time 90.61499999370426
loadBasis.js:50 transcoder time 91.24499990139157
loadBasis.js:50 transcoder time 140.09999996051192
loadBasis.js:50 transcoder time 146.88500005286187
loadBasis.js:50 transcoder time 185.29499997384846
loadBasis.js:50 transcoder time 161.40499990433455
loadBasis.js:50 transcoder time 129.19000000692904
loadBasis.js:50 transcoder time 130.23999996948987
loadBasis.js:50 transcoder time 130.64500002656132
loadBasis.js:50 transcoder time 235.76500010676682
loadBasis.js:50 transcoder time 230.03000009339303
2loadBasis.js:50 transcoder time 229.26499997265637
loadBasis.js:50 transcoder time 229.3000000063338
loadBasis.js:50 transcoder time 231.83499998413026
loadBasis.js:50 transcoder time 231.41500004567206
loadBasis.js:50 transcoder time 231.02000006474555
loadBasis.js:50 transcoder time 231.29999998491257
loadBasis.js:50 transcoder time 230.89000000618398
loadBasis.js:50 transcoder time 231.08000005595386
loadBasis.js:50 transcoder time 231.5449999878183
loadBasis.js:50 transcoder time 414.8999999742955
loadBasis.js:50 transcoder time 418.8349999021739
loadBasis.js:50 transcoder time 419.4200000492856
loadBasis.js:50 transcoder time 419.6300000185147
loadBasis.js:50 transcoder time 420.74999993201345
loadBasis.js:50 transcoder time 421.37500003445894
loadBasis.js:50 transcoder time 421.74499994143844
loadBasis.js:50 transcoder time 422.1499999985099
loadBasis.js:50 transcoder time 422.56500001531094
loadBasis.js:50 transcoder time 455.22999996319413
loadBasis.js:50 transcoder time 455.6950000114739
...
...
loadBasis.js:50 transcoder time 1810.8800000045449
loadBasis.js:50 transcoder time 1811.1100000096485
loadBasis.js:50 transcoder time 1811.4550000755116
loadBasis.js:50 transcoder time 1811.8800000520423
loadBasis.js:50 transcoder time 1812.2149999253452
loadBasis.js:50 transcoder time 1812.5649999128655
loadBasis.js:50 transcoder time 1813.620000029914
loadBasis.js:50 transcoder time 1852.0400000270456
loadBasis.js:50 transcoder time 1949.2649999447167
loadBasis.js:50 transcoder time 1954.4249998871237
loadBasis.js:50 transcoder time 2137.7550000324845
loadBasis.js:50 transcoder time 2148.020000080578
```

* my question

How to improve the decoding speed, I use the way traversal is necessary, because there will be a lot of textures to deal with.

**Comment by richgel999** [comment] 2021-03-13 20:42
Hi - I'm not very experienced with Javascript. The JS wrappers are extremely thin API's overtop of the existing C++ transcoder API's. For fastest transcoding, you should transcode all mipmap levels of a texture, one at a time, before moving on to the next texture. If you could explain what you're doing and what the problem is in more detail, I may be able to help better.

**Comment by PolanZ** [comment] 2021-03-15 06:35
> Hi - I'm not very experienced with Javascript. The JS wrappers are extremely thin API's overtop of the existing C++ transcoder API's. For fastest transcoding, you should transcode all mipmap levels of a texture, one at a time, before moving on to the next texture. If you could explain what you're doing and what the problem is in more detail, I may be able to help better.

ty.  I try to use the number of CPU cores provided by the browser `navigator.hardwareConcurrency`. At this time, the decoding will not be blocked, and the decoding time is between 10ms and 150ms, but the total decoding time is not better optimized.

**Comment by richgel999** [comment] 2021-03-17 03:09
> and the decoding time is between 10ms and 150ms, but the total decoding time is not better optimized.

Ok, got it. Transcoding is too slow for you. Are you using UASTC or ETC1S files? What resolution are your files? What browser.

**Comment by PolanZ** [comment] 2021-03-17 07:38
> Are you using UASTC or ETC1S files? What resolution are your files? Also, what browser?

Use ETC1S file.  and browser are Google Chrome 88 or Microsoft Edge 89

the file is 1024 * 1024 resolution.

the log infomation:
```
Loading assets/test.basis...
Done loading .basis file, decoded header:
------
getFileDesc():
version: 19
us per frame: 0
total images: 1
userdata0: 0 userdata1: 0
texFormat: 0
yFlipped: false hasAlphaSlices: false
numEndpoints: 1095
endpointPaletteOfs: 215
endpointPaletteLen: 2275
numSelectors: 2724
selectorPaletteOfs: 2490
selectorPaletteLen: 6384
tablesOfs: 8874
tablesLen: 1018
------
getImageDesc() for all images:
image: 0
origWidth: 1024 origWidth: 1024
numBlocksX: 256 origWidth: 256
numLevels: 6
alphaFlag: false iframeFlag: false
getImageLevelDesc() for all mipmap levels:
level: 0 rgb_file_offset: 9892 rgb_file_len: 148653
level: 1 rgb_file_offset: 158545 rgb_file_len: 8307
level: 2 rgb_file_offset: 166852 rgb_file_len: 479
level: 3 rgb_file_offset: 167331 rgb_file_len: 34
level: 4 rgb_file_offset: 167365 rgb_file_len: 4
level: 5 rgb_file_offset: 167369 rgb_file_len: 4
------
format: 6
isUncompressedFormat: false bytesPerBlockOrPixel: 16
width: 1024
height: 1024
images: 1
first image mipmap levels: 6
has_alpha: 0
14.14ms transcoding time
```

Basis file.
[test.zip](https://github.com/BinomialLLC/basis_universal/files/6154464/test.zip)


simple file transcode is fine. Maybe I need to consult the JS expert?

**Comment by richgel999** [comment] 2021-03-18 21:54
WASM is around 2x slower than native for transcoding. It is possible to transcode multiple mipmap levels (and textures) on different threads, if that helps.

**Comment by richgel999** [comment] 2021-12-27 07:29
Another round of optimizations that will improve performance (mostly encoding) in WASM are coming in a week or two. I'm going to close this for now, feel free to reopen or file a new bug if this remains an issue. Thanks!

**Comment by PolanZ** [comment] 2021-12-27 07:29
您的邮件我已收到，会尽快回复。亲

**Closed by richgel999** 2021-12-27 07:29 UTC
