### ISSUE TITLE
Possible wrapping leading to wrong colours in PVRTC decoding

### ISSUE THREAD

**Issue by nh2** [BinomialLLC/basis_universal#78] opened 2019-09-27 21:28 UTC
On iOS only (not on Android or e.g. Chrome on Linux, where everything looks good), the emscripten-compiled Basis decoder apparently generates wrong colours at the texture edges along the X-axis. 

I reported this issue here, with a full repro:

https://github.com/mrdoob/three.js/issues/17597

Repro link: https://nh2.me/webgl-basis-problem/ -- it looks different on iOS than on other platforms.

Linux:

![image](https://user-images.githubusercontent.com/399535/65803339-a0b73180-e17e-11e9-8efb-9839ba528eec.png)

iOS:

![image](https://user-images.githubusercontent.com/399535/65803353-a745a900-e17e-11e9-86d2-5ece5e729d35.png)

But it is very possible that it's not a three.js, but a Basis problem.

Looking at the pixel colours carefully, it seems colours "fading" into the edge are exactly the colours at the opposing end of the image.

Are you aware of anything that could cause this? Perhaps some modulo operation that takes "surrounding pixels" account wrapping around the image boundaries?

**Comment by richgel999** [comment] 2019-09-27 23:45
Can you send us the texture so we can verify that it's being handled correctly?

**Comment by sehurlburt** [comment] 2019-09-27 23:51
I agree with Rich that it may just be not handled correctly, but I wanted to point out that one reason you're only seeing this only on iOS is because of PVRTC-- this is a very PVRTC-looking issue. I think we can find a way to avoid this particular artifact in this case. And if it turns out it can be avoided, increasing the resolution is often a go-to fix on iOS web and I think why it's still the standard format there. But in general, I really would like iOS WebKit to adopt ASTC or even ETC. ASTC in particular is a higher quality format, whereas iOS web currently has no options for higher quality. iOS hardware, however, has the capability to use it and in fact many native apps do so with great success. I hope we can see this from them soon.

**Comment by richgel999** [comment] 2019-09-27 23:55
I'll try and grab your texture and see what's happening.

I'm not positive what's going on, but here are two ideas:

The PVRTC1 format supports both wrap and clamp addressing, and the encoder needs to know how you will be sampling the texture to produce the best/correct results. Otherwise colors can appear to "bleed" or wrap across the left/right or top/bottom of the texture.

The "cDecodeFlagsPVRTCWrapAddressing" transcoder flag controls this. This flag causes the transcoder to assume you will be using wrap addressing when sampling the texture, instead of clamping. If you use clamp address while sampling, but encode with wrapping enabled, you can get bleeding across the sides of the texture. 

I'm not positive, but this could be the issue. If this is the case, another workaround is to make sure your texture has a "gutter" around all the edges, of at least ~4 pixels.

Another idea: PVRTC1's quality is lower than all the other formats, and it has unique artifacts. We use a real-time encoder to convert the .basis ETC1S data to PVRTC1, which tends to "smooth out" sharp edges/harsh transitions. PVRTC1 is a very unforgiving format to transcode to in real-time. Our real-time PVRTC1 encoder has a set of predictable artifacts, which is about the best we can say about it.

One easy workaround (if this is the case) is to enlarge your texture, which I know isn't great because that costs more memory.

We currently use a 2 step encoder for PVRTC1. We could expand this to 3 steps (optionally), which would reduce but not eliminate the artifacts. This would slow down transcoder and we would probably need another ~64K lookup table.

The real fundamental problem is that you are very likely running on iOS hardware that fully supports ASTC (and PVRTC2), but WebKit on iOS just doesn't expose either format. It only exposes PVRTC1. This is very unfortunate, because this format is very difficult for us to handle.

**Comment by nh2** [comment] 2019-09-28 06:26
> Can you send us the texture so we can verify that it's being handled correctly?

It's in my repro link, direct texture URL is https://nh2.me/webgl-basis-problem/HyASShGs0WEZasDAd9ajk3.basis

**Comment by nh2** [comment] 2019-09-28 06:27
More info: If I encode the same texture with `PVRTexToolCLI`, this problem does not occur.

**Comment by nh2** [comment] 2019-09-28 06:46
OK, I have a much better repro now that I think confirms that the problem is in Basis:

https://nh2.me/webgl-basis-problem2/

Full files so you can run it yourself: [webgl-basis-problem.zip](https://github.com/BinomialLLC/basis_universal/files/3665160/webgl-basis-problem.zip) -- extract and self-host e.g. with `python3 -m http.server`.

It uses a cube as geometry, to exclude that three.js's geometry rendering has anything to do with it.

The cube doesn't spin so it's easy to inspect.

The original image is https://nh2.me/webgl-basis-problem2/smiley.png -- a smiley image where one side of the mouth touches an image edge, and the rest of that image edge is painted green.

![image](https://user-images.githubusercontent.com/399535/65812742-ed752980-e1cb-11e9-809c-d2a8cc5f985d.png)

On Linux it looks like this:

![image](https://user-images.githubusercontent.com/399535/65812768-5197ed80-e1cc-11e9-9046-693ecdc5f6e0.png)

On iOS:

![image](https://user-images.githubusercontent.com/399535/65812770-58266500-e1cc-11e9-82a3-23f4ae0d07f3.png)

See how the red part of the mouth "smears over to the other side" of the image, wrapping around.

**Comment by nh2** [comment] 2019-09-28 06:58
@richgel999 Thanks for the thorough explanation.

Looking at my simplified pictures above, the wrap/clamp explanation looks most likely to me.

The iOS screenshot suggests that the wrap-around of red pixels is exactly 3 pixels wide in this case.

**Comment by nh2** [comment] 2019-09-28 07:51
In https://github.com/mrdoob/three.js/blob/e8145dcaa83f57da82a3d3d413c89e34b9f01571/examples/jsm/loaders/BasisTextureLoader.js#L474

is the call to `transcodeImage`; annotating it with the parameter names from [here](https://github.com/BinomialLLC/basis_universal/blob/2af4f7453399d386606c561c0f7893f0aba0c89c/webgl/transcoder/basis_wrappers.cpp#L258):

```
var status = basisFile.transcodeImage(
  dst,                                                       // const emscripten::val& dst
  0,                                                         // uint32_t imageIndex
  mip,                                                       // uint32_t levelIndex
  config.format,                                             // uint32_t format
  config.etcSupported ? 0 : ( config.dxtSupported ? 1 : 0 ), // uint32_t pvrtcWrapAddressing
  0                                                          // uint32_t getAlphaForOpaqueFormats
);
```

I notice the problem on iOS no matter whether I set `pvrtcWrapAddressing` to `0` or `1`.

**Comment by nh2** [comment] 2019-09-28 08:44
Another question:

Is it sensible that three.js sets `pvrtcWrapAddressing` to `1` if `dxtSupported`?

I see the comment

```c++
			// PVRTC1: texture will use wrap addressing vs. clamp (most PVRTC viewer tools assume wrap addressing, so we default to wrap although that can cause edge artifacts)
			cDecodeFlagsPVRTCWrapAddressing = 1,	
```

but can't quite conclude whether that means that wrap addressing should be turned on unconditionally in three.js.

Can you confirm whether wrap addressing is designed to be used when a texture is mapped onto a sphere or a torus? If yes, it should probably be an option in three.js, not something that's controlled by DXT support. (There's also the chance that this was actually supposed to control alpha support but the parameter order got mixed up, see https://github.com/mrdoob/three.js/pull/17546#commitcomment-35275564).

Though as mentioned, this is tangential to this bug, as I get my problem no matter what `pvrtcWrapAddressing` is set to.

**Comment by richgel999** [comment] 2019-09-30 01:03
> Is it sensible that three.js sets pvrtcWrapAddressing to 1 if dxtSupported?

"cDecodeFlagsPVRTCWrapAddressing" should only be specified if the texture wraps from side/side, and you will be sampling the texture with wrap (instead of clamp) addressing. Otherwise, you're going to get artifacts. (The PVRTexTool UI's viewer assumes you'll always use wrap addressing, and I don't know how to disable this, BTW.)

**Comment by nh2** [comment] 2019-09-30 01:10
> I don't know what "dxtSupported" really means in this context exactly.

It means that the browser claims to support this native texture format, e.g. https://github.com/mrdoob/three.js/blob/e6920cdf8d4a76c582f7ac91b93a1056eec740ae/examples/js/loaders/BasisTextureLoader.js#L67-L68

```javascript
		config.dxtSupported = !! renderer.extensions.get( 'WEBGL_compressed_texture_s3tc' );
		config.pvrtcSupported = !! renderer.extensions.get( 'WEBGL_compressed_texture_pvrtc' )
```

> I'll compress your smiley texture and see what happening.

Thanks, very appreciated! :+1:

**Comment by richgel999** [comment] 2019-09-30 02:22
Okay, I've reproduced the problem on iOS with the smiley texture. Thanks for providing it!

The issue is, the PVRTC1 texture sampling hardware only supports wrap addressing when it accesses the compressed blocks in the texture. It doesn't seem to matter if the user sets the texture wrap mode to gl.CLAMP_TO_EDGE, or not. Internally it always uses wrap addressing to fetch the 4 block colors before the interpolation. (This flies against all of my instincts - why would they design it that way?)

So it doesn't matter if the transcoder uses clamp addressing during encoding, because the hardware apparently can never do that. This is also backed up by studying the PVR SDK example that shows how to unpack PVRTC1 textures (PVRTDecompress.cpp) - it only supports wrap addressing. 

So my assumption that the user could force CLAMP addressing and the hardware would magically just clamp at the boundaries was false. This means I can eliminate the transcoder WrapAddressing flag because the hardware always uses wrap no matter what.

So what this boils down to is: The real-time encoding algorithm we're using isn't as strong as PVRTexTool's. If there are red blocks on the rightmost side of a texture, this red color will slightly "leak" to the left side and vice versa. It's unclear what we can do yet. I've verified that the only other available open source real-time PVRTC1 encoder also behaves in exactly this way with the smiley texture:
https://roartindon.blogspot.com/2014/08/pvr-texture-compression-exploration.html

PVRTexTool somehow avoids this issue on this texture. I'll examine PVRTexTool's output and see if we can reproduce its behavior, but no guarantees. 

PVRTexTool has an option to "Add a mirrored border" to work around issues like this, interestingly:
http://cdn.imgtec.com/sdk-documentation/PVRTexTool.User+Manual.pdf

**Comment by richgel999** [comment] 2019-09-30 02:24
For now, my main recommendation is to try and avoid placing content on the 4 pixel borders of textures that clashes with the opposite border, or you may have issues.

**Comment by richgel999** [comment] 2020-03-21 07:03
We have a fix for this, but it slows down PVRTC1 transcoding. By a factor of 2x or more without SIMD. It also improves quality.

Our plan is to get this checked in as an option.

**Comment by hjlld** [comment] 2020-04-14 03:44
@richgel999 hi, i just encountered the same issue, glad to see it has been resolved and thanks alot.  is it alreay released within verssion 1.12?

**Closed** 2020-12-18 10:10 UTC

**Comment by nh2** [comment] 2020-12-25 00:09
What was the solution (commit)?

**Comment by nh2** [comment] 2024-02-10 01:07
@richgel999 short ping on this question ^
