### ISSUE TITLE
UASTC blurry normal maps on iOS Safari

### ISSUE THREAD

**Issue by ThorstenBux** [BinomialLLC/basis_universal#149] opened 2020-06-03 02:59 UTC
Hi there, I'm very new to basisu and I'm a bit hesitant to put that question into an issue but I don't know where else to ask. 

Whenever I'm creating compressed normal maps with UASTC they look somewhat blurry on iOS. What I do is I run the texture compression with `-mipmap -normal_map -uastc -uastc_level 2` and use that as a texture on a plane in WebGL. It does work alright however the outcome is very blurry and a low res jpeg leads to a much better result than the basis texture.
This is the texture:
https://drive.google.com/file/d/1aAZtXsKMwBpty3njY3hTD9CfQ1yWLNtp/view?usp=sharing

**Comment by willeastcott** [comment] 2020-06-03 08:52
You might be interested to see what the PlayCanvas engine does to mitigate the terrible impact PVR compression has on normal maps:

https://github.com/playcanvas/engine/blob/master/src/resources/texture.js#L315

For normal maps, we compress to GGGR format (which mitigates cross-channel leakage under block compression) and then [unswizzle to 565 uncompressed](https://github.com/playcanvas/engine/blob/master/src/resources/basis.js#L171) when PVR is the target compression format.

The results are actually pretty good!

**Comment by cwoffenden** [comment] 2020-06-03 15:22
While iOS natively supports ASTC (from the Air 2 onwards, see here for some benchmarks I did of [texture memory size, etc.](https://github.com/BinomialLLC/basis_universal/files/4724302/iPad.GLES.pdf)) WebGL doesn't expose it.

We're able to ship native for iOS but Will's suggestion above or transcode to RGB if you can afford the memory hit.

**Comment by kenrussell** [comment] 2020-06-03 18:34
Please watch for and test with any forthcoming developer builds of Safari for iOS from Apple. ASTC and ETC compressed texture support are present in top-of-tree WebKit's WebGL implementation.

**Comment by willeastcott** [comment] 2020-06-07 09:16
Yeah, I saw those commits on the Webkit project, @kenrussell. Weren't they made some time around late last year? It does seem to take a long time for them to percolate through to Safari.

**Comment by kenrussell** [comment] 2020-06-08 17:21
The changes to enable ETC and ASTC compressed textures in WebKit on iOS - https://bugs.webkit.org/show_bug.cgi?id=197900 and https://bugs.webkit.org/show_bug.cgi?id=202836 - were essentially predicated on switching to use ANGLE as WebKit's WebGL backend. This took a long time to stabilize, but to the best of my knowledge. is on track for public release.

**Comment by richgel999** [comment] 2020-08-04 21:03
> Whenever I'm creating compressed normal maps with UASTC they look somewhat blurry on iOS.

The issue is very unlikely to be UASTC, because that's extremely high quality (even on normal maps). Basis Universal's real-time PVRTC encoder does its best, but it's a *very* challenging format to encode in real-time at high quality.  The current PVRTC transcoder usually looks OK with sprites/diffuse/specular textures, but on normal maps it's unlikely to work well. 

I have some enhancements to the encoder in a prototype, but they slow it down, perhaps unstably so, and I doubt it would help out much if at all with normal maps. PVRTC is becoming less and less important as time goes by on iOS, thankfully.

I'm going to close this issue (it's a known problem, and there have been some other helpful replies). Let me know if there's anything I can do.

**Closed by richgel999** 2020-08-04 21:03 UTC

**Comment by ThorstenBux** [comment] 2020-08-04 21:26
Thank you @richgel999. Yes I found that it is a known issue and good to know that it might go away with time. 

I should have closed the ticket already. Thanks again for your support, this awesome library and for cleaning up the ticket.
